### ISSUE TITLE
Consider an approach on style names to avoid conflict with existing projects

### ISSUE THREAD

**Issue by pbolduc** [bcgov/react-shared-components#4]
CSS styles like "label" is pretty generic and is likely to conflict with existing project or other libraries.  This project should consider approaches used on other libs,

Fluent UI - https://developer.microsoft.com/en-us/fluentui#/

A simple approach would be to prefix all styles with `bcgov-`  or shorter `bc-`

```
<Input
  input={{
    ...input,
    styling: "editable-white"
  }}
  onChange={action("onChange")}
/>
```

vs 

```
<Input
  input={{
    ...input,
    styling: "bcgov-editable-white"
  }}
  onChange={action("onChange")}
/>
```

**Comment by alexjoybc** [comment]
@pbolduc good suggestion!

**Comment by sdevalapurkar-bcgov** [comment]
Yes thank you, as discussed we will look into this :)
and will follow a pattern as shown here for all components: https://github.com/bcgov/react-shared-components/blob/master/src/components/callout/Callout.css#L1
